name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [ "main" ]

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      sh: ${{ steps.filter.outputs.sh }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            java:
              - 'src/**'
              - 'gradle/**'
              - './*.gradle'
            sh:
              - 'scripts/**'
  java-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.java == 'true' }}
    uses: ./.github/workflows/java_build.yml
  sh-build:
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.sh == 'true' }}
    uses: ./.github/workflows/sh_build.yml
  build-result:
    runs-on: ubuntu-latest
    needs: [java-build, sh-build]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect build result
        run: |
          if echo java-${{ needs.java-build.result }},sh-${{ needs.sh-build.result }} | grep -E 'cancelled|failure' -o > null
          then
            echo "There are failed/cancelled builds"
            exit 1 
          else
            echo "All builds are successful/skipped"
            exit 0
          fi
